module LoanConfiguration
where

import LoanConfigurationType

-- ==========================================
-- Configurations of some predefined products
-- ==========================================
confList = [confClassic,confBalloon,confClassicDreba,confClassicDrebaCar,
            confVario,confVario2,confVario3,confZielkauf,confDLClassical,
            confZielkaufAllianz,confRevBalloonAlianz,confRevBalloonAlianz',
            confClassic1Free,confOneIntFree]

confClassic = ClassicCalcConf { feeType = Financed,
                                clType = Classical,
                                base = Effective,
                                freq = Monthly,
                                calendar = Y360,
                                rounding = Truncated,
                                amorType = AmorDirect,
                                minFstInstDur = 15,
                                cccERType = ERProportional,
                                cccMaxDur = 0,
                                cccMinInstAmt = 0,
                                cccInstAdj = FstInstallmentAdjusted,
                                ccConfName = "CoFi Classic",
                                ccConfFun = "confClassic"
                                }
confBalloon = ClassicCalcConf { feeType = Financed,
                                clType = Balloon,
                                base = Effective,
                                freq = Monthly,
                                calendar = Y360,
                                rounding = Truncated,
                                amorType = AmorDirect,
                                minFstInstDur = 15,
                                cccERType = ERProportional,
                                cccMaxDur = 84,
                                cccMinInstAmt = 0,
                                cccInstAdj = FstInstallmentAdjusted,
                                ccConfName = "CoFi Balloon",
                                ccConfFun = "confBalloon"
                                }
confClassicDreba = ClassicCalcConf { feeType = Financed,
                                     clType = Classical,
                                     base = Effective,
                                     freq = Monthly,
                                     calendar = Y360,
                                     rounding = Truncated,
                                     amorType = AmorDirect,
                                     minFstInstDur = 30,
                                     cccERType = ERProportional,
                                     cccMaxDur = 0,
                                     cccMinInstAmt = 0,
                                     cccInstAdj = FstInstallmentAdjusted,
                                     ccConfName = "Coba Classic",
                                     ccConfFun = "confClassicDreba"
                                     }
confClassicDrebaCar = ClassicCalcConf { feeType = Financed,
                                        clType = Classical,
                                        base = Effective,
                                        freq = Monthly,
                                        calendar = Y360,
                                        rounding = Truncated,
                                        amorType = AmorDirect,
                                        minFstInstDur = 30,
                                        cccERType = ERProportional,
                                        cccMaxDur = 0,
                                        cccMinInstAmt = 0,
                                        cccInstAdj = NoAdjustment,
                                        ccConfName = "Coba Classic Car",
                                        ccConfFun = "confClassicDrebaCar"
                                        }
confVario = ClassicCalcConf  { feeType = Financed,
                                clType = Vario2,
                                base = Effective,
                                freq = Monthly,
                                calendar = Y360,
                                rounding = Truncated,
                                amorType = AmorDirect,
                                minFstInstDur = 20,
                                cccERType = ERNoInstInc,
                                cccMaxDur = 84,
                                cccMinInstAmt = 1500,
                                cccInstAdj = FstInstallmentAdjusted,
                                ccConfName = "DL Vario1",
                                ccConfFun = "confVario"
                                }
confVario2 = ClassicCalcConf  { feeType = Financed,
                                clType = Vario2,
                                base = Effective,
                                freq = Monthly,
                                calendar = Y360,
                                rounding = Truncated,
                                amorType = AmorDirect,
                                minFstInstDur = 20,
                                cccERType = ERNoInstInc,
                                cccMaxDur = 96,
                                cccMinInstAmt = 1500,
                                cccInstAdj = FstInstallmentAdjusted,
                                ccConfName = "DL Vario2",
                                ccConfFun = "confVario2"
                                }
confVario3 = ClassicCalcConf  { feeType = Financed,
                                clType = Vario3,
                                base = Effective,
                                freq = Monthly,
                                calendar = Y360,
                                rounding = Truncated,
                                amorType = AmorDirect,
                                minFstInstDur = 20,
                                cccERType = ERNoInstInc,
                                cccMaxDur = 96,
                                cccMinInstAmt = 1500,
                                cccInstAdj = FstInstallmentAdjusted,
                                ccConfName = "DL Vario3",
                                ccConfFun = "confVario3"
                                }
confZielkauf = ClassicCalcConf  { feeType = PaidIn1stInst,
                                  clType = Zielkauf,
                                  base = Effective,
                                  freq = Monthly,
                                  calendar = Y360,
                                  rounding = Truncated,
                                  amorType = AmorDirect,
                                  minFstInstDur = 15,
                                  cccERType = ERProportional,
                                  cccMaxDur = 6,
                                  cccMinInstAmt = 1500,
                                  cccInstAdj = FstInstallmentAdjusted,
                                  ccConfName = "Zielkauf",
                                  ccConfFun = "confZielkauf"
                                }
confDLClassical = ClassicCalcConf  { feeType = Financed,
                                     clType = Classical,
                                     base = Effective,
                                     freq = Monthly,
                                     calendar = Y360,
                                     rounding = Truncated,
                                     amorType = AmorDirect,
                                     minFstInstDur = 20,
                                     cccERType = ERNoInstInc,
                                     cccMaxDur = 0,
                                     cccMinInstAmt = 0,
                                     cccInstAdj = FstInstallmentAdjusted,
                                     ccConfName = "DL Classic",
                                     ccConfFun = "confDLClassical"
                                     }
confZielkaufAllianz = ClassicCalcConf  { feeType = PaidIn1stInst,
                                  clType = Zielkauf,
                                  base = Effective,
                                  freq = Monthly,
                                  calendar = Y360,
                                  rounding = Truncated,
                                  amorType = AmorDirect,
                                  minFstInstDur = 30,
                                  cccERType = ERProportional,
                                  cccMaxDur = 6,
                                  cccMinInstAmt = 1500,
                                  cccInstAdj = FstInstallmentAdjusted,
                                  ccConfName = "Allianz Zielkauf",
                                  ccConfFun = "confZielkaufAllianz"
                                }

confRevBalloonAlianz = ClassicCalcConf {  feeType = Financed,
                                          clType = SecuredBalloon,
                                          base = Effective,
                                          freq = Monthly,
                                          calendar = Y360,
                                          rounding = Truncated,
                                          amorType = AmorDirect,
                                          minFstInstDur = 30,
                                          cccERType = ERProportional,
                                          cccMaxDur = 84,
                                          cccMinInstAmt = 0,
                                          cccInstAdj = FstInstallmentAdjusted,
                                          ccConfName = "Allianz Secured Balloon",
                                          ccConfFun = "confRevBalloonAlianz"
                                }
confRevBalloonAlianz' = ClassicCalcConf {  feeType = Financed,
                                          clType = SecuredBalloon,
                                          base = Effective,
                                          freq = Monthly,
                                          calendar = Y360,
                                          rounding = Truncated,
                                          amorType = AmorDirect,
                                          minFstInstDur = 30,
                                          cccERType = ERProportional,
                                          cccMaxDur = 84,
                                          cccMinInstAmt = 0,
                                          cccInstAdj = NoAdjustment,
                                          ccConfName = "Allianz Secured Balloon Bis",
                                          ccConfFun = "confRevBalloonAlianz'"
                                }

confClassic1Free = ClassicCalcConf { feeType = Financed,
                                     clType = ClassicalOneFreeInterest,
                                     base = Effective,
                                     freq = Monthly,
                                     calendar = Y360,
                                     rounding = Truncated,
                                     amorType = AmorDirect,
                                     minFstInstDur = 15,
                                     cccERType = ERProportional,
                                     cccMaxDur = 0,
                                     cccMinInstAmt = 0,
                                     cccInstAdj = NoAdjustment,
                                     ccConfName = "CFG Phone Pilot Prototype 1",
                                     ccConfFun = "confClassic1Free"
                                }
confOneIntFree = ClassicCalcConf { feeType = Financed,
                                     clType = OneFreeInterest,
                                     base = Effective,
                                     freq = Monthly,
                                     calendar = Y360,
                                     rounding = Truncated,
                                     amorType = AmorDirect,
                                     minFstInstDur = 15,
                                     cccERType = ERProportional,
                                     cccMaxDur = 0,
                                     cccMinInstAmt = 0,
                                     cccInstAdj = NoAdjustment,
                                     ccConfName = "CFG Phone Pilot Prototype 2",
                                     ccConfFun = "confOneIntFree"
                                }

